### ISSUE TITLE
Are master and ghost entities guaranteed to return lower order entities in the same order?

### ISSUE THREAD

**Issue by raovgarimella** [MeshToolkit/MSTK#58]
@lipnikov asks if it guaranteed in MSTK that master and ghost entities will return lower order entities in the same order (edges of a face or faces of region)?

**Comment by raovgarimella** [comment]
Yes, by the way the parallel partitioning, send-receive protocols and mesh query operators are designed, a side effect of this is that master and ghost entities will have the same hierarchical topology. Please file a bug request if you find an instance where it is not so.

**Comment by lipnikov** [comment]
I can add last message to Mesh.hh? after description of face_get_cells OR you will do it yourself?

**Comment by raovgarimella** [comment]
yes you can
